const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'Nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirts',
    },
    {
      name: 'Adidas fit shirt',
      slug: 'Adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'High quality shirts',
    },
    {
      name: 'Nike slim pants',
      slug: 'Nike-slim-pants',
      category: 'pants',
      image: '/images/p3.jpg',
      price: 320,
      countInStock: 8,
      brand: 'Nike',
      rating: 4.4,
      numReviews: 8,
      description: 'High quality products',
    },
    {
      name: 'Adidas fit pants',
      slug: 'Adidas-fit-pants',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 240,
      countInStock: 13,
      brand: 'Adidas',
      rating: 4.6,
      numReviews: 13,
      description: 'High quality pants',
    },
  ],
};

export default data